apiVersion: apps/v1
kind: Deployment
metadata:
  name: journal-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: journal-api
  template:
    metadata:
      labels:
        app: journal-api
    spec:
      containers:
      - name: api
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000

        envFrom:
        - secretRef:
            name: journal-api-secrets

        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
