name: Build - Push

on:
  push:
    branches: [main]
  workflow_run:
    workflows: ["Test"]
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GAR_LOCATION: us-central1
      REPOSITORY: journal-repo
      IMAGE: journal-api
      GKE_CLUSTER: journal-cluster
      GKE_ZONE: us-central1
    steps:
      - uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Image
        run: |
          TAG="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}"
          docker build -t "$TAG:${{ github.sha }}" -t "$TAG:latest" .
          docker push "$TAG:${{ github.sha }}"
          docker push "$TAG:latest"
